
const types = {
    ADD_UTANG: "ADD_UTANG",
    DELETE_UTANG: "DELETE_UTANG",
    TOGGLE_EDIT: "TOGGLE_EDIT",
    EDIT_DETAILS: "EDIT_DETAILS",
    TOGGLE_PAYMENT: "TOGGLE_PAYMENT",
    ADD_PAYMENT: "ADD_PAYMENT",
    COMPLETE_UTANG: "COMPLETE_UTANG",
    CLOSE_POPUP: "CLOSE_POPUP"
}

export default types;